CREATE DATABASE IF NOT EXISTS spendsmart

USE spendsmart

CREATE TABLE spendsmart.Users ( 
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(100) NOT NULL,
  password TEXT NOT NULL
)
